language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.11.2

script: 'bundle exec rake test'

notifications:
  email:
    recipients:
      - eturino@artirix.com
    on_failure: change
    on_success: never
